/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness Check */
        get: operations["readiness_check_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/solar-to-lunar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solar To Lunar */
        post: operations["solar_to_lunar_calendar_solar_to_lunar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/lunar-to-solar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lunar To Solar */
        post: operations["lunar_to_solar_calendar_lunar_to_solar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/stem-branch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Stem Branch */
        post: operations["get_stem_branch_calendar_stem_branch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/can-chi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Can Chi Alias
         * @deprecated
         * @description Deprecated: use `/calendar/stem-branch`.
         */
        post: operations["get_can_chi_alias_calendar_can_chi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/earth-plate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Earth Plate */
        post: operations["generate_earth_plate_chart_earth_plate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/dia-ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Dia Ban Alias
         * @deprecated
         * @description Deprecated: use `/chart/earth-plate`.
         */
        post: operations["generate_dia_ban_alias_chart_dia_ban_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Chart */
        post: operations["generate_chart_chart_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Chart */
        post: operations["analyze_chart_chart_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Batch Charts */
        post: operations["generate_batch_charts_chart_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/hour-branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hour Branches */
        get: operations["get_hour_branches_info_hour_branches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/gio-chi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gio Chi Alias
         * @deprecated
         * @description Deprecated: use `/info/hour-branches`.
         */
        get: operations["get_gio_chi_alias_info_gio_chi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/stars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Star Catalog */
        get: operations["get_star_catalog_info_stars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/sao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sao Alias
         * @deprecated
         * @description Deprecated: use `/info/stars`.
         */
        get: operations["get_sao_alias_info_sao_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/elements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Elements Info */
        get: operations["get_elements_info_info_elements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/stem-branch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stem Branch Info */
        get: operations["get_stem_branch_info_info_stem_branch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info/can-chi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Can Chi Info Alias
         * @deprecated
         */
        get: operations["get_can_chi_info_alias_info_can_chi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchChartRequest */
        BatchChartRequest: {
            /** Charts */
            charts: components["schemas"]["BirthInfoRequest"][];
        };
        /** BatchChartResponse */
        BatchChartResponse: {
            /** Total */
            total: number;
            /** Successful */
            successful: number;
            /** Failed */
            failed: number;
            /** Results */
            results: (components["schemas"]["ChartResponse"] | components["schemas"]["ErrorResponse"])[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
        };
        /**
         * BirthInfoRequest
         * @description Birth data used to generate a chart.
         * @example {
         *       "day": 15,
         *       "month": 8,
         *       "year": 1990,
         *       "hour": 7,
         *       "gender": 1,
         *       "is_solar": true,
         *       "timezone": 7,
         *       "name": "Nguyễn Văn A",
         *       "view_year": 2026,
         *       "birth_place": {
         *         "label": "Hà Nội",
         *         "longitude": 105.85,
         *         "latitude": 21.03
         *       },
         *       "clock_time": null,
         *       "life_context": {
         *         "marital_status": "married",
         *         "children_status": "has_children"
         *       }
         *     }
         */
        BirthInfoRequest: {
            /**
             * Day
             * @description Birth day (1-31)
             */
            day: number;
            /**
             * Month
             * @description Birth month (1-12)
             */
            month: number;
            /**
             * Year
             * @description Birth year
             */
            year: number;
            /**
             * Hour
             * @description Birth hour branch index (1=Zi ... 12=Hai)
             */
            hour: number;
            /**
             * Gender
             * @description 1=male, -1=female
             * @enum {integer}
             */
            gender: 1 | -1;
            /**
             * Is Solar
             * @description True if Gregorian date, False if lunar
             * @default true
             */
            is_solar: boolean;
            /**
             * Timezone
             * @description Timezone offset (default +7 VN)
             * @default 7
             */
            timezone: number;
            /**
             * Name
             * @description Optional display name
             */
            name?: string | null;
            /**
             * View Year
             * @description Year used for monthly luck overlay (Gregorian)
             */
            view_year?: number | null;
            /** @description Optional birth location for true solar time longitude correction */
            birth_place?: components["schemas"]["BirthPlace"] | null;
            /**
             * Clock Time
             * @description Optional civil clock time HH:mm.
             */
            clock_time?: string | null;
            /** @description Optional marital/children context for Phu thê / Tử tức readings only */
            life_context?: components["schemas"]["LifeContext"] | null;
        };
        /** ChartAnalysisResponse */
        ChartAnalysisResponse: {
            birth_info: components["schemas"]["BirthInfoRequest"];
            life_palace_analysis?: components["schemas"]["PalaceAnalysis"] | null;
            career_palace_analysis?: components["schemas"]["PalaceAnalysis"] | null;
            wealth_palace_analysis?: components["schemas"]["PalaceAnalysis"] | null;
            /** Overall Strength */
            overall_strength: string;
            /** Lucky Elements */
            lucky_elements: string[];
            /** Unlucky Elements */
            unlucky_elements: string[];
            /** Major Life Events */
            major_life_events: Record<string, never>[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
        };
        /**
         * ChartFormation
         * @description Detected chart formation / pattern (cách cục).
         */
        ChartFormation: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** ChartMeta */
        ChartMeta: {
            /** Ben Ming Name */
            ben_ming_name?: string | null;
            /** Nayin */
            nayin?: string | null;
            /** Year Yin Yang */
            year_yin_yang?: string | null;
            /** Life Yin Yang Status */
            life_yin_yang_status?: string | null;
            /** Ming Zhu */
            ming_zhu?: string | null;
            /** Shen Zhu */
            shen_zhu?: string | null;
            /** Sheng Ke Status */
            sheng_ke_status?: string | null;
            /** Wu Xing Ju Name */
            wu_xing_ju_name?: string | null;
            /** Wu Xing Ju */
            wu_xing_ju?: number | null;
            /** View Year */
            view_year?: number | null;
            /** View Year Branch */
            view_year_branch?: string | null;
            /** Hour Input */
            hour_input?: number | null;
            /** Hour Applied */
            hour_applied?: number | null;
            /** True Solar Offset Minutes */
            true_solar_offset_minutes?: number | null;
            /**
             * True Solar Applied
             * @default false
             */
            true_solar_applied: boolean;
            /** Clock Time */
            clock_time?: string | null;
            /** Birth Place Label */
            birth_place_label?: string | null;
            /** Longitude Offset Minutes */
            longitude_offset_minutes?: number | null;
            /** Equation Of Time Minutes */
            equation_of_time_minutes?: number | null;
        };
        /** ChartResponse */
        ChartResponse: {
            birth_info: components["schemas"]["BirthInfoRequest"];
            lunar_date: components["schemas"]["LunarDateResponse"];
            stem_branch: components["schemas"]["StemBranchResponse"];
            earth_plate: components["schemas"]["EarthPlateResponse"];
            /** Formations */
            formations?: components["schemas"]["ChartFormation"][];
            chart_meta?: components["schemas"]["ChartMeta"] | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
        };
        /** EarthPlateResponse */
        EarthPlateResponse: {
            /** Lunar Birth Month */
            lunar_birth_month: number;
            /** Lunar Birth Hour */
            lunar_birth_hour: number;
            /** Life Palace */
            life_palace: number;
            /** Body Palace */
            body_palace: number;
            /** Wu Xing Ju */
            wu_xing_ju: number;
            /** Wu Xing Ju Name */
            wu_xing_ju_name: string;
            /** Palaces */
            palaces: components["schemas"]["PalaceInfo"][];
            /** Formations */
            formations?: components["schemas"]["ChartFormation"][];
            /** Taboo Palaces */
            taboo_palaces?: string[];
            chart_meta?: components["schemas"]["ChartMeta"] | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Error */
            error: string;
            /** Detail */
            detail?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** LunarDateResponse */
        LunarDateResponse: {
            /** Day */
            day: number;
            /** Month */
            month: number;
            /** Year */
            year: number;
            /**
             * Is Leap Month
             * @default false
             */
            is_leap_month: boolean;
        };
        /** PalaceAnalysis */
        PalaceAnalysis: {
            /** Index */
            index: number;
            /** Branch Name */
            branch_name: string;
            /** Palace Name */
            palace_name: string;
            /** Major Stars */
            major_stars: string[];
            /** Support Stars */
            support_stars: string[];
            /** Element */
            element: string;
            /** Strength */
            strength: string;
            /** Positive Aspects */
            positive_aspects: string[];
            /** Negative Aspects */
            negative_aspects: string[];
        };
        /** PalaceInfo */
        PalaceInfo: {
            /** Index */
            index: number;
            /** Branch Name */
            branch_name: string;
            /** Palace Name */
            palace_name?: string | null;
            /** Palace Element */
            palace_element: string;
            /** Yin Yang */
            yin_yang: number;
            /** Stem */
            stem?: number | null;
            /** Stem Name */
            stem_name?: string | null;
            /** Stars */
            stars?: components["schemas"]["StarInfo"][];
            /** Interpretations */
            interpretations?: components["schemas"]["StarInterpretation"][];
            /** Da Xian Age */
            da_xian_age?: number | null;
            /** Xiao Xian Branch */
            xiao_xian_branch?: string | null;
            /** Yue Xian */
            yue_xian?: number | null;
            /**
             * Is Body Palace
             * @default false
             */
            is_body_palace: boolean;
            /**
             * Is Xun
             * @default false
             */
            is_xun: boolean;
            /**
             * Is Triet
             * @default false
             */
            is_triet: boolean;
        };
        /** SolarDateResponse */
        SolarDateResponse: {
            /** Day */
            day: number;
            /** Month */
            month: number;
            /** Year */
            year: number;
        };
        /** StarCatalogItem */
        StarCatalogItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Element */
            element?: string | null;
            /** Category */
            category?: number | null;
            /** Category Label */
            category_label?: string | null;
            /** Direction */
            direction?: string | null;
            /** Yin Yang */
            yin_yang?: unknown | null;
            /**
             * Is Chang Sheng
             * @default false
             */
            is_chang_sheng: boolean;
            /** Description */
            description?: string | null;
            /** Meaning */
            meaning?: string | null;
        };
        /** StarCatalogResponse */
        StarCatalogResponse: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["StarCatalogItem"][];
            /**
             * Miao Wang
             * @default {
             *       "M": "Miếu",
             *       "V": "Vượng",
             *       "Đ": "Đắc",
             *       "D": "Đắc",
             *       "B": "Bình",
             *       "H": "Hãm"
             *     }
             */
            miao_wang: {
                [key: string]: string;
            };
            /**
             * Category Labels
             * @default {
             *       "1": "major_star",
             *       "2": "minor_star",
             *       "3": "noble_star",
             *       "4": "authority_star",
             *       "5": "blessing_star",
             *       "6": "literary_star",
             *       "7": "pavilion_star",
             *       "8": "peach_blossom_star",
             *       "11": "malefic_star",
             *       "12": "defeat_star",
             *       "13": "obscure_star",
             *       "14": "lust_star",
             *       "15": "punishment_star",
             *       "16": "minor_star"
             *     }
             */
            category_labels: {
                [key: string]: string;
            };
        };
        /** StarInfo */
        StarInfo: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Element */
            element?: string | null;
            /** Category */
            category?: number | null;
            /** Category Label */
            category_label?: string | null;
            /** Miao Wang */
            miao_wang?: string | null;
            /** Miao Wang Label */
            miao_wang_label?: string | null;
            /** Mutagen */
            mutagen?: string | null;
            /** Direction */
            direction?: string | null;
            /** Yin Yang */
            yin_yang?: unknown | null;
            /**
             * Is Chang Sheng
             * @default false
             */
            is_chang_sheng: boolean;
            /** Is Auspicious */
            is_auspicious?: boolean | null;
            /** Palace Position */
            palace_position?: number | null;
        };
        /**
         * StarInterpretation
         * @description Reading for one star in a palace (from the interpretation knowledge base).
         */
        StarInterpretation: {
            /** Star */
            star: string;
            /** Interpretation */
            interpretation: string;
        };
        /** StemBranchPair */
        StemBranchPair: {
            /** Stem */
            stem: number;
            /** Branch */
            branch: number;
            /** Stem Name */
            stem_name: string;
            /** Branch Name */
            branch_name: string;
            /** Label */
            label: string;
        };
        /**
         * StemBranchResponse
         * @description Full stem–branch for year/month/day/hour.
         */
        StemBranchResponse: {
            /** Year Stem */
            year_stem: number;
            /** Year Branch */
            year_branch: number;
            /** Month Stem */
            month_stem: number;
            /** Year Stem Name */
            year_stem_name: string;
            /** Year Branch Name */
            year_branch_name: string;
            /** Month Branch */
            month_branch?: number | null;
            /** Month Stem Name */
            month_stem_name?: string | null;
            /** Month Branch Name */
            month_branch_name?: string | null;
            /** Day Stem */
            day_stem?: number | null;
            /** Day Branch */
            day_branch?: number | null;
            /** Day Stem Name */
            day_stem_name?: string | null;
            /** Day Branch Name */
            day_branch_name?: string | null;
            /** Hour Stem */
            hour_stem?: number | null;
            /** Hour Branch */
            hour_branch?: number | null;
            /** Hour Stem Name */
            hour_stem_name?: string | null;
            /** Hour Branch Name */
            hour_branch_name?: string | null;
            year?: components["schemas"]["StemBranchPair"] | null;
            month?: components["schemas"]["StemBranchPair"] | null;
            day?: components["schemas"]["StemBranchPair"] | null;
            hour?: components["schemas"]["StemBranchPair"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * BirthPlace
         * @description Birth location for true-solar-time longitude correction.
         */
        BirthPlace: {
            /**
             * Label
             * @description Display label (e.g. Hà Nội)
             */
            label?: string | null;
            /**
             * Longitude
             * @description Geographic longitude in degrees (required when birth_place is set)
             */
            longitude: number;
            /**
             * Latitude
             * @description Geographic latitude in degrees (optional)
             */
            latitude?: number | null;
        };
        /**
         * LifeContext
         * @description Optional life-context hints for spouse/children palace readings only.
         */
        LifeContext: {
            /**
             * Marital Status
             * @description single | married | divorced | remarried; omit/null = undisclosed
             */
            marital_status?: ("single" | "married" | "divorced" | "remarried") | null;
            /**
             * Children Status
             * @description has_children | no_children; omit/null = undisclosed
             */
            children_status?: ("has_children" | "no_children") | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_check_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    solar_to_lunar_calendar_solar_to_lunar_post: {
        parameters: {
            query: {
                day: number;
                month: number;
                year: number;
                timezone?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LunarDateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lunar_to_solar_calendar_lunar_to_solar_post: {
        parameters: {
            query: {
                day: number;
                month: number;
                year: number;
                is_leap_month?: boolean;
                timezone?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolarDateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stem_branch_calendar_stem_branch_post: {
        parameters: {
            query: {
                day: number;
                month: number;
                year: number;
                is_solar?: boolean;
                timezone?: number;
                hour?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StemBranchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_can_chi_alias_calendar_can_chi_post: {
        parameters: {
            query?: {
                day?: number | null;
                month?: number | null;
                year?: number | null;
                ngay?: number | null;
                thang?: number | null;
                nam?: number | null;
                is_solar?: boolean;
                duong_lich?: boolean | null;
                timezone?: number;
                hour?: number | null;
                gio?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StemBranchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_earth_plate_chart_earth_plate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BirthInfoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarthPlateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_dia_ban_alias_chart_dia_ban_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BirthInfoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarthPlateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_chart_chart_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BirthInfoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_chart_chart_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BirthInfoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_batch_charts_chart_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchChartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchChartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hour_branches_info_hour_branches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_gio_chi_alias_info_gio_chi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_star_catalog_info_stars_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StarCatalogResponse"];
                };
            };
        };
    };
    get_sao_alias_info_sao_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StarCatalogResponse"];
                };
            };
        };
    };
    get_elements_info_info_elements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_stem_branch_info_info_stem_branch_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_can_chi_info_alias_info_can_chi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_stats_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
